server:
  port: 8887

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#  properties:
#    hibernate:
#      format_sql: true
#  datasource:
#    driver-class-name:
#    url:
#    username:
#    password:
