server:
  port: 8888

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /Users/Administrator/Desktop
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: market
    password: market
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
    show-sql: true

