server:
  port: 8888

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/origin/
      suffix: .jsp
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: market
    password: market
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      format_sql: true
    show-sql: true   
    
mybatis:
  mapper-locations: classpath:sqls/*.xml
  type-aliases-package: com.ticket.market.vo

 