server:
  port: 8888

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#  jpa:
#    hibernate:
#      ddl-auto: create
#  properties:
#    hibernate:
#      format_sql: true
#  datasource:
#    driver-class-name:
#    url:
#    username:
#    password:
